"""empty message

Revision ID: 08d63f2baa07
Revises: 57534d3795df
Create Date: 2020-07-23 16:11:37.036648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d63f2baa07'
down_revision = '57534d3795df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tarefa', 'dataConclusao',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tarefa', 'dataConclusao',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
