"""empty message

Revision ID: 154df2131999
Revises: 198371046dd1
Create Date: 2020-07-13 20:50:44.760039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '154df2131999'
down_revision = '198371046dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nome', table_name='Item')
    op.drop_index('ix_Raridade_recompensa', table_name='Raridade')
    op.drop_index('nome', table_name='Tarefa')
    op.drop_index('recompensa', table_name='Tarefa')
    op.alter_column('usuario_grupo', 'Grupo_idGrupo',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('usuario_grupo', 'Usuario_idUsuario',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('usuario_tarefa', 'Tarefa_idTarefa',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('usuario_tarefa', 'Usuario_idUsuario',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario_tarefa', 'Usuario_idUsuario',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('usuario_tarefa', 'Tarefa_idTarefa',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('usuario_grupo', 'Usuario_idUsuario',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('usuario_grupo', 'Grupo_idGrupo',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index('recompensa', 'Tarefa', ['recompensa'], unique=True)
    op.create_index('nome', 'Tarefa', ['nome'], unique=True)
    op.create_index('ix_Raridade_recompensa', 'Raridade', ['recompensa'], unique=False)
    op.create_index('nome', 'Item', ['nome'], unique=True)
    # ### end Alembic commands ###
