"""empty message

Revision ID: 51d71058f375
Revises: 7529365ab2a0
Create Date: 2020-07-14 21:48:54.204461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d71058f375'
down_revision = '7529365ab2a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuario', sa.Column('senha', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Usuario', 'senha')
    # ### end Alembic commands ###
